# Setup
title:               Naman Kumar
tagline:             'Fullstack Engineer'
url:                 https://thenamankumar.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Naman Kumar
  url:               https://twitter.com/TheNamanKumar
  email:             naman@outlook.in

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
